// Code generated by ent, DO NOT EDIT.

package productinfo

import (
	"products-service/internal/app/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldDeletedAt, v))
}

// InfoTypesID applies equality check predicate on the "info_types_id" field. It's identical to InfoTypesIDEQ.
func InfoTypesID(v int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldInfoTypesID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLTE(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotNull(FieldDeletedAt))
}

// InfoTypesIDEQ applies the EQ predicate on the "info_types_id" field.
func InfoTypesIDEQ(v int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldInfoTypesID, v))
}

// InfoTypesIDNEQ applies the NEQ predicate on the "info_types_id" field.
func InfoTypesIDNEQ(v int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNEQ(FieldInfoTypesID, v))
}

// InfoTypesIDIn applies the In predicate on the "info_types_id" field.
func InfoTypesIDIn(vs ...int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIn(FieldInfoTypesID, vs...))
}

// InfoTypesIDNotIn applies the NotIn predicate on the "info_types_id" field.
func InfoTypesIDNotIn(vs ...int) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotIn(FieldInfoTypesID, vs...))
}

// InfoTypesIDIsNil applies the IsNil predicate on the "info_types_id" field.
func InfoTypesIDIsNil() predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIsNull(FieldInfoTypesID))
}

// InfoTypesIDNotNil applies the NotNil predicate on the "info_types_id" field.
func InfoTypesIDNotNil() predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotNull(FieldInfoTypesID))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.ProductInfo {
	return predicate.ProductInfo(sql.FieldContainsFold(FieldValue, v))
}

// HasInfoType applies the HasEdge predicate on the "info_type" edge.
func HasInfoType() predicate.ProductInfo {
	return predicate.ProductInfo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InfoTypeTable, InfoTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInfoTypeWith applies the HasEdge predicate on the "info_type" edge with a given conditions (other predicates).
func HasInfoTypeWith(preds ...predicate.InfoTypes) predicate.ProductInfo {
	return predicate.ProductInfo(func(s *sql.Selector) {
		step := newInfoTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductHasInfo applies the HasEdge predicate on the "product_has_info" edge.
func HasProductHasInfo() predicate.ProductInfo {
	return predicate.ProductInfo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProductHasInfoTable, ProductHasInfoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductHasInfoWith applies the HasEdge predicate on the "product_has_info" edge with a given conditions (other predicates).
func HasProductHasInfoWith(preds ...predicate.ProductHasInfo) predicate.ProductInfo {
	return predicate.ProductInfo(func(s *sql.Selector) {
		step := newProductHasInfoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductInfo) predicate.ProductInfo {
	return predicate.ProductInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductInfo) predicate.ProductInfo {
	return predicate.ProductInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductInfo) predicate.ProductInfo {
	return predicate.ProductInfo(sql.NotPredicates(p))
}
