// Code generated by ent, DO NOT EDIT.

package tools

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tools type in the database.
	Label = "tools"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeToolHasProduct holds the string denoting the tool_has_product edge name in mutations.
	EdgeToolHasProduct = "tool_has_product"
	// Table holds the table name of the tools in the database.
	Table = "tools"
	// ToolHasProductTable is the table that holds the tool_has_product relation/edge.
	ToolHasProductTable = "tool_has_products"
	// ToolHasProductInverseTable is the table name for the ToolHasProduct entity.
	// It exists in this package in order to avoid circular dependency with the "toolhasproduct" package.
	ToolHasProductInverseTable = "tool_has_products"
	// ToolHasProductColumn is the table column denoting the tool_has_product relation/edge.
	ToolHasProductColumn = "tools_id"
)

// Columns holds all SQL columns for tools fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldDeletedAt,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Tools queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByToolHasProductCount orders the results by tool_has_product count.
func ByToolHasProductCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newToolHasProductStep(), opts...)
	}
}

// ByToolHasProduct orders the results by tool_has_product terms.
func ByToolHasProduct(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToolHasProductStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newToolHasProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToolHasProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ToolHasProductTable, ToolHasProductColumn),
	)
}
