services:
  products_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: products_service
    ports:
      - '0.0.0.0:5001:5001'
    networks:
      whatsapp_bot:
        ipv4_address: 172.18.0.5

networks:
  whatsapp_bot:
    name: whatsapp_bot
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16