// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"products-service/internal/app/ent/featuresvaluestypes"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FeaturesValuesTypes is the model entity for the FeaturesValuesTypes schema.
type FeaturesValuesTypes struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int `json:"updated_by,omitempty"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy *int `json:"deleted_by,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FeaturesValuesTypesQuery when eager-loading is set.
	Edges        FeaturesValuesTypesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FeaturesValuesTypesEdges holds the relations/edges for other nodes in the graph.
type FeaturesValuesTypesEdges struct {
	// ProductInfo holds the value of the product_info edge.
	ProductInfo []*ProductInfo `json:"product_info,omitempty"`
	// FeatureValues holds the value of the feature_values edge.
	FeatureValues []*FeaturesValues `json:"feature_values,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductInfoOrErr returns the ProductInfo value or an error if the edge
// was not loaded in eager-loading.
func (e FeaturesValuesTypesEdges) ProductInfoOrErr() ([]*ProductInfo, error) {
	if e.loadedTypes[0] {
		return e.ProductInfo, nil
	}
	return nil, &NotLoadedError{edge: "product_info"}
}

// FeatureValuesOrErr returns the FeatureValues value or an error if the edge
// was not loaded in eager-loading.
func (e FeaturesValuesTypesEdges) FeatureValuesOrErr() ([]*FeaturesValues, error) {
	if e.loadedTypes[1] {
		return e.FeatureValues, nil
	}
	return nil, &NotLoadedError{edge: "feature_values"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FeaturesValuesTypes) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case featuresvaluestypes.FieldID, featuresvaluestypes.FieldCreatedBy, featuresvaluestypes.FieldUpdatedBy, featuresvaluestypes.FieldDeletedBy:
			values[i] = new(sql.NullInt64)
		case featuresvaluestypes.FieldName:
			values[i] = new(sql.NullString)
		case featuresvaluestypes.FieldCreatedAt, featuresvaluestypes.FieldUpdatedAt, featuresvaluestypes.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FeaturesValuesTypes fields.
func (fvt *FeaturesValuesTypes) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case featuresvaluestypes.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fvt.ID = int(value.Int64)
		case featuresvaluestypes.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				fvt.CreatedAt = value.Time
			}
		case featuresvaluestypes.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				fvt.UpdatedAt = value.Time
			}
		case featuresvaluestypes.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				fvt.DeletedAt = new(time.Time)
				*fvt.DeletedAt = value.Time
			}
		case featuresvaluestypes.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				fvt.CreatedBy = int(value.Int64)
			}
		case featuresvaluestypes.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				fvt.UpdatedBy = int(value.Int64)
			}
		case featuresvaluestypes.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				fvt.DeletedBy = new(int)
				*fvt.DeletedBy = int(value.Int64)
			}
		case featuresvaluestypes.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				fvt.Name = new(string)
				*fvt.Name = value.String
			}
		default:
			fvt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FeaturesValuesTypes.
// This includes values selected through modifiers, order, etc.
func (fvt *FeaturesValuesTypes) Value(name string) (ent.Value, error) {
	return fvt.selectValues.Get(name)
}

// QueryProductInfo queries the "product_info" edge of the FeaturesValuesTypes entity.
func (fvt *FeaturesValuesTypes) QueryProductInfo() *ProductInfoQuery {
	return NewFeaturesValuesTypesClient(fvt.config).QueryProductInfo(fvt)
}

// QueryFeatureValues queries the "feature_values" edge of the FeaturesValuesTypes entity.
func (fvt *FeaturesValuesTypes) QueryFeatureValues() *FeaturesValuesQuery {
	return NewFeaturesValuesTypesClient(fvt.config).QueryFeatureValues(fvt)
}

// Update returns a builder for updating this FeaturesValuesTypes.
// Note that you need to call FeaturesValuesTypes.Unwrap() before calling this method if this FeaturesValuesTypes
// was returned from a transaction, and the transaction was committed or rolled back.
func (fvt *FeaturesValuesTypes) Update() *FeaturesValuesTypesUpdateOne {
	return NewFeaturesValuesTypesClient(fvt.config).UpdateOne(fvt)
}

// Unwrap unwraps the FeaturesValuesTypes entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fvt *FeaturesValuesTypes) Unwrap() *FeaturesValuesTypes {
	_tx, ok := fvt.config.driver.(*txDriver)
	if !ok {
		panic("ent: FeaturesValuesTypes is not a transactional entity")
	}
	fvt.config.driver = _tx.drv
	return fvt
}

// String implements the fmt.Stringer.
func (fvt *FeaturesValuesTypes) String() string {
	var builder strings.Builder
	builder.WriteString("FeaturesValuesTypes(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fvt.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fvt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fvt.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := fvt.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", fvt.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", fvt.UpdatedBy))
	builder.WriteString(", ")
	if v := fvt.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := fvt.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// FeaturesValuesTypesSlice is a parsable slice of FeaturesValuesTypes.
type FeaturesValuesTypesSlice []*FeaturesValuesTypes
