// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"products-service/internal/app/ent/features"
	"products-service/internal/app/ent/featuresvalues"
	"products-service/internal/app/ent/predicate"
	"products-service/internal/app/ent/producthasfeature"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeaturesQuery is the builder for querying Features entities.
type FeaturesQuery struct {
	config
	ctx                   *QueryContext
	order                 []features.OrderOption
	inters                []Interceptor
	predicates            []predicate.Features
	withFeatureValues     *FeaturesValuesQuery
	withProductHasFeature *ProductHasFeatureQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FeaturesQuery builder.
func (fq *FeaturesQuery) Where(ps ...predicate.Features) *FeaturesQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FeaturesQuery) Limit(limit int) *FeaturesQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FeaturesQuery) Offset(offset int) *FeaturesQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FeaturesQuery) Unique(unique bool) *FeaturesQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FeaturesQuery) Order(o ...features.OrderOption) *FeaturesQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryFeatureValues chains the current query on the "feature_values" edge.
func (fq *FeaturesQuery) QueryFeatureValues() *FeaturesValuesQuery {
	query := (&FeaturesValuesClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(features.Table, features.FieldID, selector),
			sqlgraph.To(featuresvalues.Table, featuresvalues.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, features.FeatureValuesTable, features.FeatureValuesColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProductHasFeature chains the current query on the "product_has_feature" edge.
func (fq *FeaturesQuery) QueryProductHasFeature() *ProductHasFeatureQuery {
	query := (&ProductHasFeatureClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(features.Table, features.FieldID, selector),
			sqlgraph.To(producthasfeature.Table, producthasfeature.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, features.ProductHasFeatureTable, features.ProductHasFeatureColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Features entity from the query.
// Returns a *NotFoundError when no Features was found.
func (fq *FeaturesQuery) First(ctx context.Context) (*Features, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{features.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FeaturesQuery) FirstX(ctx context.Context) *Features {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Features ID from the query.
// Returns a *NotFoundError when no Features ID was found.
func (fq *FeaturesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{features.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FeaturesQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Features entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Features entity is found.
// Returns a *NotFoundError when no Features entities are found.
func (fq *FeaturesQuery) Only(ctx context.Context) (*Features, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{features.Label}
	default:
		return nil, &NotSingularError{features.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FeaturesQuery) OnlyX(ctx context.Context) *Features {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Features ID in the query.
// Returns a *NotSingularError when more than one Features ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FeaturesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{features.Label}
	default:
		err = &NotSingularError{features.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FeaturesQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FeaturesSlice.
func (fq *FeaturesQuery) All(ctx context.Context) ([]*Features, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryAll)
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Features, *FeaturesQuery]()
	return withInterceptors[[]*Features](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FeaturesQuery) AllX(ctx context.Context) []*Features {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Features IDs.
func (fq *FeaturesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryIDs)
	if err = fq.Select(features.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FeaturesQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FeaturesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryCount)
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FeaturesQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FeaturesQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FeaturesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryExist)
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FeaturesQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FeaturesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FeaturesQuery) Clone() *FeaturesQuery {
	if fq == nil {
		return nil
	}
	return &FeaturesQuery{
		config:                fq.config,
		ctx:                   fq.ctx.Clone(),
		order:                 append([]features.OrderOption{}, fq.order...),
		inters:                append([]Interceptor{}, fq.inters...),
		predicates:            append([]predicate.Features{}, fq.predicates...),
		withFeatureValues:     fq.withFeatureValues.Clone(),
		withProductHasFeature: fq.withProductHasFeature.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithFeatureValues tells the query-builder to eager-load the nodes that are connected to
// the "feature_values" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FeaturesQuery) WithFeatureValues(opts ...func(*FeaturesValuesQuery)) *FeaturesQuery {
	query := (&FeaturesValuesClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFeatureValues = query
	return fq
}

// WithProductHasFeature tells the query-builder to eager-load the nodes that are connected to
// the "product_has_feature" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FeaturesQuery) WithProductHasFeature(opts ...func(*ProductHasFeatureQuery)) *FeaturesQuery {
	query := (&ProductHasFeatureClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withProductHasFeature = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Features.Query().
//		GroupBy(features.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FeaturesQuery) GroupBy(field string, fields ...string) *FeaturesGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FeaturesGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = features.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Features.Query().
//		Select(features.FieldCreatedAt).
//		Scan(ctx, &v)
func (fq *FeaturesQuery) Select(fields ...string) *FeaturesSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FeaturesSelect{FeaturesQuery: fq}
	sbuild.label = features.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FeaturesSelect configured with the given aggregations.
func (fq *FeaturesQuery) Aggregate(fns ...AggregateFunc) *FeaturesSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FeaturesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !features.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FeaturesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Features, error) {
	var (
		nodes       = []*Features{}
		_spec       = fq.querySpec()
		loadedTypes = [2]bool{
			fq.withFeatureValues != nil,
			fq.withProductHasFeature != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Features).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Features{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withFeatureValues; query != nil {
		if err := fq.loadFeatureValues(ctx, query, nodes,
			func(n *Features) { n.Edges.FeatureValues = []*FeaturesValues{} },
			func(n *Features, e *FeaturesValues) { n.Edges.FeatureValues = append(n.Edges.FeatureValues, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withProductHasFeature; query != nil {
		if err := fq.loadProductHasFeature(ctx, query, nodes,
			func(n *Features) { n.Edges.ProductHasFeature = []*ProductHasFeature{} },
			func(n *Features, e *ProductHasFeature) {
				n.Edges.ProductHasFeature = append(n.Edges.ProductHasFeature, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FeaturesQuery) loadFeatureValues(ctx context.Context, query *FeaturesValuesQuery, nodes []*Features, init func(*Features), assign func(*Features, *FeaturesValues)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Features)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(featuresvalues.FieldFeatureID)
	}
	query.Where(predicate.FeaturesValues(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(features.FeatureValuesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FeatureID
		if fk == nil {
			return fmt.Errorf(`foreign-key "feature_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "feature_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fq *FeaturesQuery) loadProductHasFeature(ctx context.Context, query *ProductHasFeatureQuery, nodes []*Features, init func(*Features), assign func(*Features, *ProductHasFeature)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Features)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(producthasfeature.FieldFeatureID)
	}
	query.Where(predicate.ProductHasFeature(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(features.ProductHasFeatureColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FeatureID
		if fk == nil {
			return fmt.Errorf(`foreign-key "feature_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "feature_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *FeaturesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FeaturesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(features.Table, features.Columns, sqlgraph.NewFieldSpec(features.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, features.FieldID)
		for i := range fields {
			if fields[i] != features.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FeaturesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(features.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = features.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FeaturesGroupBy is the group-by builder for Features entities.
type FeaturesGroupBy struct {
	selector
	build *FeaturesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FeaturesGroupBy) Aggregate(fns ...AggregateFunc) *FeaturesGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FeaturesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, ent.OpQueryGroupBy)
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeaturesQuery, *FeaturesGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FeaturesGroupBy) sqlScan(ctx context.Context, root *FeaturesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FeaturesSelect is the builder for selecting fields of Features entities.
type FeaturesSelect struct {
	*FeaturesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FeaturesSelect) Aggregate(fns ...AggregateFunc) *FeaturesSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FeaturesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, ent.OpQuerySelect)
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeaturesQuery, *FeaturesSelect](ctx, fs.FeaturesQuery, fs, fs.inters, v)
}

func (fs *FeaturesSelect) sqlScan(ctx context.Context, root *FeaturesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
