// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"products-service/internal/app/ent/predicate"
	"products-service/internal/app/ent/pricetype"
	"products-service/internal/app/ent/productprices"
	"products-service/internal/app/ent/products"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductPricesQuery is the builder for querying ProductPrices entities.
type ProductPricesQuery struct {
	config
	ctx           *QueryContext
	order         []productprices.OrderOption
	inters        []Interceptor
	predicates    []predicate.ProductPrices
	withProduct   *ProductsQuery
	withPriceType *PriceTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductPricesQuery builder.
func (ppq *ProductPricesQuery) Where(ps ...predicate.ProductPrices) *ProductPricesQuery {
	ppq.predicates = append(ppq.predicates, ps...)
	return ppq
}

// Limit the number of records to be returned by this query.
func (ppq *ProductPricesQuery) Limit(limit int) *ProductPricesQuery {
	ppq.ctx.Limit = &limit
	return ppq
}

// Offset to start from.
func (ppq *ProductPricesQuery) Offset(offset int) *ProductPricesQuery {
	ppq.ctx.Offset = &offset
	return ppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppq *ProductPricesQuery) Unique(unique bool) *ProductPricesQuery {
	ppq.ctx.Unique = &unique
	return ppq
}

// Order specifies how the records should be ordered.
func (ppq *ProductPricesQuery) Order(o ...productprices.OrderOption) *ProductPricesQuery {
	ppq.order = append(ppq.order, o...)
	return ppq
}

// QueryProduct chains the current query on the "product" edge.
func (ppq *ProductPricesQuery) QueryProduct() *ProductsQuery {
	query := (&ProductsClient{config: ppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productprices.Table, productprices.FieldID, selector),
			sqlgraph.To(products.Table, products.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productprices.ProductTable, productprices.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPriceType chains the current query on the "price_type" edge.
func (ppq *ProductPricesQuery) QueryPriceType() *PriceTypeQuery {
	query := (&PriceTypeClient{config: ppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productprices.Table, productprices.FieldID, selector),
			sqlgraph.To(pricetype.Table, pricetype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productprices.PriceTypeTable, productprices.PriceTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductPrices entity from the query.
// Returns a *NotFoundError when no ProductPrices was found.
func (ppq *ProductPricesQuery) First(ctx context.Context) (*ProductPrices, error) {
	nodes, err := ppq.Limit(1).All(setContextOp(ctx, ppq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productprices.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppq *ProductPricesQuery) FirstX(ctx context.Context) *ProductPrices {
	node, err := ppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductPrices ID from the query.
// Returns a *NotFoundError when no ProductPrices ID was found.
func (ppq *ProductPricesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(1).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productprices.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppq *ProductPricesQuery) FirstIDX(ctx context.Context) int {
	id, err := ppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductPrices entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductPrices entity is found.
// Returns a *NotFoundError when no ProductPrices entities are found.
func (ppq *ProductPricesQuery) Only(ctx context.Context) (*ProductPrices, error) {
	nodes, err := ppq.Limit(2).All(setContextOp(ctx, ppq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productprices.Label}
	default:
		return nil, &NotSingularError{productprices.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppq *ProductPricesQuery) OnlyX(ctx context.Context) *ProductPrices {
	node, err := ppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductPrices ID in the query.
// Returns a *NotSingularError when more than one ProductPrices ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppq *ProductPricesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(2).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productprices.Label}
	default:
		err = &NotSingularError{productprices.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppq *ProductPricesQuery) OnlyIDX(ctx context.Context) int {
	id, err := ppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductPricesSlice.
func (ppq *ProductPricesQuery) All(ctx context.Context) ([]*ProductPrices, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryAll)
	if err := ppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductPrices, *ProductPricesQuery]()
	return withInterceptors[[]*ProductPrices](ctx, ppq, qr, ppq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ppq *ProductPricesQuery) AllX(ctx context.Context) []*ProductPrices {
	nodes, err := ppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductPrices IDs.
func (ppq *ProductPricesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ppq.ctx.Unique == nil && ppq.path != nil {
		ppq.Unique(true)
	}
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryIDs)
	if err = ppq.Select(productprices.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppq *ProductPricesQuery) IDsX(ctx context.Context) []int {
	ids, err := ppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppq *ProductPricesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryCount)
	if err := ppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ppq, querierCount[*ProductPricesQuery](), ppq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ppq *ProductPricesQuery) CountX(ctx context.Context) int {
	count, err := ppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppq *ProductPricesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryExist)
	switch _, err := ppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ppq *ProductPricesQuery) ExistX(ctx context.Context) bool {
	exist, err := ppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductPricesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppq *ProductPricesQuery) Clone() *ProductPricesQuery {
	if ppq == nil {
		return nil
	}
	return &ProductPricesQuery{
		config:        ppq.config,
		ctx:           ppq.ctx.Clone(),
		order:         append([]productprices.OrderOption{}, ppq.order...),
		inters:        append([]Interceptor{}, ppq.inters...),
		predicates:    append([]predicate.ProductPrices{}, ppq.predicates...),
		withProduct:   ppq.withProduct.Clone(),
		withPriceType: ppq.withPriceType.Clone(),
		// clone intermediate query.
		sql:  ppq.sql.Clone(),
		path: ppq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *ProductPricesQuery) WithProduct(opts ...func(*ProductsQuery)) *ProductPricesQuery {
	query := (&ProductsClient{config: ppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ppq.withProduct = query
	return ppq
}

// WithPriceType tells the query-builder to eager-load the nodes that are connected to
// the "price_type" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *ProductPricesQuery) WithPriceType(opts ...func(*PriceTypeQuery)) *ProductPricesQuery {
	query := (&PriceTypeClient{config: ppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ppq.withPriceType = query
	return ppq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductPrices.Query().
//		GroupBy(productprices.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppq *ProductPricesQuery) GroupBy(field string, fields ...string) *ProductPricesGroupBy {
	ppq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductPricesGroupBy{build: ppq}
	grbuild.flds = &ppq.ctx.Fields
	grbuild.label = productprices.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProductPrices.Query().
//		Select(productprices.FieldCreatedAt).
//		Scan(ctx, &v)
func (ppq *ProductPricesQuery) Select(fields ...string) *ProductPricesSelect {
	ppq.ctx.Fields = append(ppq.ctx.Fields, fields...)
	sbuild := &ProductPricesSelect{ProductPricesQuery: ppq}
	sbuild.label = productprices.Label
	sbuild.flds, sbuild.scan = &ppq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductPricesSelect configured with the given aggregations.
func (ppq *ProductPricesQuery) Aggregate(fns ...AggregateFunc) *ProductPricesSelect {
	return ppq.Select().Aggregate(fns...)
}

func (ppq *ProductPricesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ppq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ppq); err != nil {
				return err
			}
		}
	}
	for _, f := range ppq.ctx.Fields {
		if !productprices.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppq.path != nil {
		prev, err := ppq.path(ctx)
		if err != nil {
			return err
		}
		ppq.sql = prev
	}
	return nil
}

func (ppq *ProductPricesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductPrices, error) {
	var (
		nodes       = []*ProductPrices{}
		_spec       = ppq.querySpec()
		loadedTypes = [2]bool{
			ppq.withProduct != nil,
			ppq.withPriceType != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductPrices).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductPrices{config: ppq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ppq.withProduct; query != nil {
		if err := ppq.loadProduct(ctx, query, nodes, nil,
			func(n *ProductPrices, e *Products) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := ppq.withPriceType; query != nil {
		if err := ppq.loadPriceType(ctx, query, nodes, nil,
			func(n *ProductPrices, e *PriceType) { n.Edges.PriceType = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ppq *ProductPricesQuery) loadProduct(ctx context.Context, query *ProductsQuery, nodes []*ProductPrices, init func(*ProductPrices), assign func(*ProductPrices, *Products)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductPrices)
	for i := range nodes {
		if nodes[i].ProductID == nil {
			continue
		}
		fk := *nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(products.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ppq *ProductPricesQuery) loadPriceType(ctx context.Context, query *PriceTypeQuery, nodes []*ProductPrices, init func(*ProductPrices), assign func(*ProductPrices, *PriceType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductPrices)
	for i := range nodes {
		if nodes[i].PriceTypeID == nil {
			continue
		}
		fk := *nodes[i].PriceTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pricetype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "price_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ppq *ProductPricesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppq.querySpec()
	_spec.Node.Columns = ppq.ctx.Fields
	if len(ppq.ctx.Fields) > 0 {
		_spec.Unique = ppq.ctx.Unique != nil && *ppq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ppq.driver, _spec)
}

func (ppq *ProductPricesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productprices.Table, productprices.Columns, sqlgraph.NewFieldSpec(productprices.FieldID, field.TypeInt))
	_spec.From = ppq.sql
	if unique := ppq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ppq.path != nil {
		_spec.Unique = true
	}
	if fields := ppq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productprices.FieldID)
		for i := range fields {
			if fields[i] != productprices.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ppq.withProduct != nil {
			_spec.Node.AddColumnOnce(productprices.FieldProductID)
		}
		if ppq.withPriceType != nil {
			_spec.Node.AddColumnOnce(productprices.FieldPriceTypeID)
		}
	}
	if ps := ppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppq *ProductPricesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppq.driver.Dialect())
	t1 := builder.Table(productprices.Table)
	columns := ppq.ctx.Fields
	if len(columns) == 0 {
		columns = productprices.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppq.sql != nil {
		selector = ppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppq.ctx.Unique != nil && *ppq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ppq.predicates {
		p(selector)
	}
	for _, p := range ppq.order {
		p(selector)
	}
	if offset := ppq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductPricesGroupBy is the group-by builder for ProductPrices entities.
type ProductPricesGroupBy struct {
	selector
	build *ProductPricesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppgb *ProductPricesGroupBy) Aggregate(fns ...AggregateFunc) *ProductPricesGroupBy {
	ppgb.fns = append(ppgb.fns, fns...)
	return ppgb
}

// Scan applies the selector query and scans the result into the given value.
func (ppgb *ProductPricesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ppgb.build.ctx, ent.OpQueryGroupBy)
	if err := ppgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductPricesQuery, *ProductPricesGroupBy](ctx, ppgb.build, ppgb, ppgb.build.inters, v)
}

func (ppgb *ProductPricesGroupBy) sqlScan(ctx context.Context, root *ProductPricesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ppgb.fns))
	for _, fn := range ppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ppgb.flds)+len(ppgb.fns))
		for _, f := range *ppgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ppgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductPricesSelect is the builder for selecting fields of ProductPrices entities.
type ProductPricesSelect struct {
	*ProductPricesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pps *ProductPricesSelect) Aggregate(fns ...AggregateFunc) *ProductPricesSelect {
	pps.fns = append(pps.fns, fns...)
	return pps
}

// Scan applies the selector query and scans the result into the given value.
func (pps *ProductPricesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pps.ctx, ent.OpQuerySelect)
	if err := pps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductPricesQuery, *ProductPricesSelect](ctx, pps.ProductPricesQuery, pps, pps.inters, v)
}

func (pps *ProductPricesSelect) sqlScan(ctx context.Context, root *ProductPricesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pps.fns))
	for _, fn := range pps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
