// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"products-service/internal/app/ent/images"
	"products-service/internal/app/ent/producthasimage"
	"products-service/internal/app/ent/products"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductHasImageCreate is the builder for creating a ProductHasImage entity.
type ProductHasImageCreate struct {
	config
	mutation *ProductHasImageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (phic *ProductHasImageCreate) SetCreatedAt(t time.Time) *ProductHasImageCreate {
	phic.mutation.SetCreatedAt(t)
	return phic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (phic *ProductHasImageCreate) SetNillableCreatedAt(t *time.Time) *ProductHasImageCreate {
	if t != nil {
		phic.SetCreatedAt(*t)
	}
	return phic
}

// SetUpdatedAt sets the "updated_at" field.
func (phic *ProductHasImageCreate) SetUpdatedAt(t time.Time) *ProductHasImageCreate {
	phic.mutation.SetUpdatedAt(t)
	return phic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (phic *ProductHasImageCreate) SetNillableUpdatedAt(t *time.Time) *ProductHasImageCreate {
	if t != nil {
		phic.SetUpdatedAt(*t)
	}
	return phic
}

// SetDeletedAt sets the "deleted_at" field.
func (phic *ProductHasImageCreate) SetDeletedAt(t time.Time) *ProductHasImageCreate {
	phic.mutation.SetDeletedAt(t)
	return phic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (phic *ProductHasImageCreate) SetNillableDeletedAt(t *time.Time) *ProductHasImageCreate {
	if t != nil {
		phic.SetDeletedAt(*t)
	}
	return phic
}

// SetCreatedBy sets the "created_by" field.
func (phic *ProductHasImageCreate) SetCreatedBy(i int) *ProductHasImageCreate {
	phic.mutation.SetCreatedBy(i)
	return phic
}

// SetUpdatedBy sets the "updated_by" field.
func (phic *ProductHasImageCreate) SetUpdatedBy(i int) *ProductHasImageCreate {
	phic.mutation.SetUpdatedBy(i)
	return phic
}

// SetDeletedBy sets the "deleted_by" field.
func (phic *ProductHasImageCreate) SetDeletedBy(i int) *ProductHasImageCreate {
	phic.mutation.SetDeletedBy(i)
	return phic
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (phic *ProductHasImageCreate) SetNillableDeletedBy(i *int) *ProductHasImageCreate {
	if i != nil {
		phic.SetDeletedBy(*i)
	}
	return phic
}

// SetImageID sets the "image_id" field.
func (phic *ProductHasImageCreate) SetImageID(i int) *ProductHasImageCreate {
	phic.mutation.SetImageID(i)
	return phic
}

// SetProductID sets the "product_id" field.
func (phic *ProductHasImageCreate) SetProductID(i int) *ProductHasImageCreate {
	phic.mutation.SetProductID(i)
	return phic
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (phic *ProductHasImageCreate) SetNillableProductID(i *int) *ProductHasImageCreate {
	if i != nil {
		phic.SetProductID(*i)
	}
	return phic
}

// SetPriority sets the "priority" field.
func (phic *ProductHasImageCreate) SetPriority(i int) *ProductHasImageCreate {
	phic.mutation.SetPriority(i)
	return phic
}

// SetProduct sets the "product" edge to the Products entity.
func (phic *ProductHasImageCreate) SetProduct(p *Products) *ProductHasImageCreate {
	return phic.SetProductID(p.ID)
}

// SetImage sets the "image" edge to the Images entity.
func (phic *ProductHasImageCreate) SetImage(i *Images) *ProductHasImageCreate {
	return phic.SetImageID(i.ID)
}

// Mutation returns the ProductHasImageMutation object of the builder.
func (phic *ProductHasImageCreate) Mutation() *ProductHasImageMutation {
	return phic.mutation
}

// Save creates the ProductHasImage in the database.
func (phic *ProductHasImageCreate) Save(ctx context.Context) (*ProductHasImage, error) {
	phic.defaults()
	return withHooks(ctx, phic.sqlSave, phic.mutation, phic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (phic *ProductHasImageCreate) SaveX(ctx context.Context) *ProductHasImage {
	v, err := phic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (phic *ProductHasImageCreate) Exec(ctx context.Context) error {
	_, err := phic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phic *ProductHasImageCreate) ExecX(ctx context.Context) {
	if err := phic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (phic *ProductHasImageCreate) defaults() {
	if _, ok := phic.mutation.CreatedAt(); !ok {
		v := producthasimage.DefaultCreatedAt()
		phic.mutation.SetCreatedAt(v)
	}
	if _, ok := phic.mutation.UpdatedAt(); !ok {
		v := producthasimage.DefaultUpdatedAt()
		phic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (phic *ProductHasImageCreate) check() error {
	if _, ok := phic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductHasImage.created_at"`)}
	}
	if _, ok := phic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductHasImage.updated_at"`)}
	}
	if _, ok := phic.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ProductHasImage.created_by"`)}
	}
	if v, ok := phic.mutation.CreatedBy(); ok {
		if err := producthasimage.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProductHasImage.created_by": %w`, err)}
		}
	}
	if _, ok := phic.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "ProductHasImage.updated_by"`)}
	}
	if v, ok := phic.mutation.UpdatedBy(); ok {
		if err := producthasimage.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "ProductHasImage.updated_by": %w`, err)}
		}
	}
	if _, ok := phic.mutation.ImageID(); !ok {
		return &ValidationError{Name: "image_id", err: errors.New(`ent: missing required field "ProductHasImage.image_id"`)}
	}
	if _, ok := phic.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ProductHasImage.priority"`)}
	}
	if len(phic.mutation.ImageIDs()) == 0 {
		return &ValidationError{Name: "image", err: errors.New(`ent: missing required edge "ProductHasImage.image"`)}
	}
	return nil
}

func (phic *ProductHasImageCreate) sqlSave(ctx context.Context) (*ProductHasImage, error) {
	if err := phic.check(); err != nil {
		return nil, err
	}
	_node, _spec := phic.createSpec()
	if err := sqlgraph.CreateNode(ctx, phic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	phic.mutation.id = &_node.ID
	phic.mutation.done = true
	return _node, nil
}

func (phic *ProductHasImageCreate) createSpec() (*ProductHasImage, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductHasImage{config: phic.config}
		_spec = sqlgraph.NewCreateSpec(producthasimage.Table, sqlgraph.NewFieldSpec(producthasimage.FieldID, field.TypeInt))
	)
	if value, ok := phic.mutation.CreatedAt(); ok {
		_spec.SetField(producthasimage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := phic.mutation.UpdatedAt(); ok {
		_spec.SetField(producthasimage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := phic.mutation.DeletedAt(); ok {
		_spec.SetField(producthasimage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := phic.mutation.CreatedBy(); ok {
		_spec.SetField(producthasimage.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	if value, ok := phic.mutation.UpdatedBy(); ok {
		_spec.SetField(producthasimage.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = value
	}
	if value, ok := phic.mutation.DeletedBy(); ok {
		_spec.SetField(producthasimage.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := phic.mutation.Priority(); ok {
		_spec.SetField(producthasimage.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if nodes := phic.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   producthasimage.ProductTable,
			Columns: []string{producthasimage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(products.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := phic.mutation.ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   producthasimage.ImageTable,
			Columns: []string{producthasimage.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(images.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ImageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductHasImageCreateBulk is the builder for creating many ProductHasImage entities in bulk.
type ProductHasImageCreateBulk struct {
	config
	err      error
	builders []*ProductHasImageCreate
}

// Save creates the ProductHasImage entities in the database.
func (phicb *ProductHasImageCreateBulk) Save(ctx context.Context) ([]*ProductHasImage, error) {
	if phicb.err != nil {
		return nil, phicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(phicb.builders))
	nodes := make([]*ProductHasImage, len(phicb.builders))
	mutators := make([]Mutator, len(phicb.builders))
	for i := range phicb.builders {
		func(i int, root context.Context) {
			builder := phicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductHasImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, phicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, phicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, phicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (phicb *ProductHasImageCreateBulk) SaveX(ctx context.Context) []*ProductHasImage {
	v, err := phicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (phicb *ProductHasImageCreateBulk) Exec(ctx context.Context) error {
	_, err := phicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phicb *ProductHasImageCreateBulk) ExecX(ctx context.Context) {
	if err := phicb.Exec(ctx); err != nil {
		panic(err)
	}
}
