// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"products-service/internal/app/ent/referencesources"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ReferenceSources is the model entity for the ReferenceSources schema.
type ReferenceSources struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferenceSourcesQuery when eager-loading is set.
	Edges        ReferenceSourcesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferenceSourcesEdges holds the relations/edges for other nodes in the graph.
type ReferenceSourcesEdges struct {
	// ProductReferences holds the value of the product_references edge.
	ProductReferences []*ProductReferences `json:"product_references,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProductReferencesOrErr returns the ProductReferences value or an error if the edge
// was not loaded in eager-loading.
func (e ReferenceSourcesEdges) ProductReferencesOrErr() ([]*ProductReferences, error) {
	if e.loadedTypes[0] {
		return e.ProductReferences, nil
	}
	return nil, &NotLoadedError{edge: "product_references"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferenceSources) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referencesources.FieldID:
			values[i] = new(sql.NullInt64)
		case referencesources.FieldName:
			values[i] = new(sql.NullString)
		case referencesources.FieldCreatedAt, referencesources.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferenceSources fields.
func (rs *ReferenceSources) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referencesources.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rs.ID = int(value.Int64)
		case referencesources.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rs.CreatedAt = value.Time
			}
		case referencesources.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				rs.DeletedAt = new(time.Time)
				*rs.DeletedAt = value.Time
			}
		case referencesources.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				rs.Name = new(string)
				*rs.Name = value.String
			}
		default:
			rs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferenceSources.
// This includes values selected through modifiers, order, etc.
func (rs *ReferenceSources) Value(name string) (ent.Value, error) {
	return rs.selectValues.Get(name)
}

// QueryProductReferences queries the "product_references" edge of the ReferenceSources entity.
func (rs *ReferenceSources) QueryProductReferences() *ProductReferencesQuery {
	return NewReferenceSourcesClient(rs.config).QueryProductReferences(rs)
}

// Update returns a builder for updating this ReferenceSources.
// Note that you need to call ReferenceSources.Unwrap() before calling this method if this ReferenceSources
// was returned from a transaction, and the transaction was committed or rolled back.
func (rs *ReferenceSources) Update() *ReferenceSourcesUpdateOne {
	return NewReferenceSourcesClient(rs.config).UpdateOne(rs)
}

// Unwrap unwraps the ReferenceSources entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rs *ReferenceSources) Unwrap() *ReferenceSources {
	_tx, ok := rs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferenceSources is not a transactional entity")
	}
	rs.config.driver = _tx.drv
	return rs
}

// String implements the fmt.Stringer.
func (rs *ReferenceSources) String() string {
	var builder strings.Builder
	builder.WriteString("ReferenceSources(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rs.ID))
	builder.WriteString("created_at=")
	builder.WriteString(rs.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := rs.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := rs.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReferenceSourcesSlice is a parsable slice of ReferenceSources.
type ReferenceSourcesSlice []*ReferenceSources
