// Code generated by ent, DO NOT EDIT.

package ent

import (
	"products-service/internal/app/ent/brand"
	"products-service/internal/app/ent/category"
	"products-service/internal/app/ent/features"
	"products-service/internal/app/ent/featuresunitvalues"
	"products-service/internal/app/ent/featuresvalues"
	"products-service/internal/app/ent/featuresvaluestypes"
	"products-service/internal/app/ent/imagefolderpath"
	"products-service/internal/app/ent/imagefoldersource"
	"products-service/internal/app/ent/images"
	"products-service/internal/app/ent/infotypes"
	"products-service/internal/app/ent/pricetype"
	"products-service/internal/app/ent/producthasfeature"
	"products-service/internal/app/ent/producthasimage"
	"products-service/internal/app/ent/producthasinfo"
	"products-service/internal/app/ent/producthasproductreference"
	"products-service/internal/app/ent/productinfo"
	"products-service/internal/app/ent/productprices"
	"products-service/internal/app/ent/productreferences"
	"products-service/internal/app/ent/products"
	"products-service/internal/app/ent/promotionhasproduct"
	"products-service/internal/app/ent/promotions"
	"products-service/internal/app/ent/referencesources"
	"products-service/internal/app/ent/schema"
	"products-service/internal/app/ent/toolhasproduct"
	"products-service/internal/app/ent/tools"
	"products-service/internal/app/ent/user"
	"products-service/internal/app/ent/varianttype"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandMixin := schema.Brand{}.Mixin()
	brandMixinFields0 := brandMixin[0].Fields()
	_ = brandMixinFields0
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescCreatedAt is the schema descriptor for created_at field.
	brandDescCreatedAt := brandMixinFields0[0].Descriptor()
	// brand.DefaultCreatedAt holds the default value on creation for the created_at field.
	brand.DefaultCreatedAt = brandDescCreatedAt.Default.(func() time.Time)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	featuresMixin := schema.Features{}.Mixin()
	featuresMixinFields0 := featuresMixin[0].Fields()
	_ = featuresMixinFields0
	featuresFields := schema.Features{}.Fields()
	_ = featuresFields
	// featuresDescCreatedAt is the schema descriptor for created_at field.
	featuresDescCreatedAt := featuresMixinFields0[0].Descriptor()
	// features.DefaultCreatedAt holds the default value on creation for the created_at field.
	features.DefaultCreatedAt = featuresDescCreatedAt.Default.(func() time.Time)
	featuresunitvaluesMixin := schema.FeaturesUnitValues{}.Mixin()
	featuresunitvaluesMixinFields0 := featuresunitvaluesMixin[0].Fields()
	_ = featuresunitvaluesMixinFields0
	featuresunitvaluesFields := schema.FeaturesUnitValues{}.Fields()
	_ = featuresunitvaluesFields
	// featuresunitvaluesDescCreatedAt is the schema descriptor for created_at field.
	featuresunitvaluesDescCreatedAt := featuresunitvaluesMixinFields0[0].Descriptor()
	// featuresunitvalues.DefaultCreatedAt holds the default value on creation for the created_at field.
	featuresunitvalues.DefaultCreatedAt = featuresunitvaluesDescCreatedAt.Default.(func() time.Time)
	featuresvaluesMixin := schema.FeaturesValues{}.Mixin()
	featuresvaluesMixinFields0 := featuresvaluesMixin[0].Fields()
	_ = featuresvaluesMixinFields0
	featuresvaluesFields := schema.FeaturesValues{}.Fields()
	_ = featuresvaluesFields
	// featuresvaluesDescCreatedAt is the schema descriptor for created_at field.
	featuresvaluesDescCreatedAt := featuresvaluesMixinFields0[0].Descriptor()
	// featuresvalues.DefaultCreatedAt holds the default value on creation for the created_at field.
	featuresvalues.DefaultCreatedAt = featuresvaluesDescCreatedAt.Default.(func() time.Time)
	featuresvaluestypesMixin := schema.FeaturesValuesTypes{}.Mixin()
	featuresvaluestypesMixinFields0 := featuresvaluestypesMixin[0].Fields()
	_ = featuresvaluestypesMixinFields0
	featuresvaluestypesFields := schema.FeaturesValuesTypes{}.Fields()
	_ = featuresvaluestypesFields
	// featuresvaluestypesDescCreatedAt is the schema descriptor for created_at field.
	featuresvaluestypesDescCreatedAt := featuresvaluestypesMixinFields0[0].Descriptor()
	// featuresvaluestypes.DefaultCreatedAt holds the default value on creation for the created_at field.
	featuresvaluestypes.DefaultCreatedAt = featuresvaluestypesDescCreatedAt.Default.(func() time.Time)
	imagefolderpathMixin := schema.ImageFolderPath{}.Mixin()
	imagefolderpathMixinFields0 := imagefolderpathMixin[0].Fields()
	_ = imagefolderpathMixinFields0
	imagefolderpathFields := schema.ImageFolderPath{}.Fields()
	_ = imagefolderpathFields
	// imagefolderpathDescCreatedAt is the schema descriptor for created_at field.
	imagefolderpathDescCreatedAt := imagefolderpathMixinFields0[0].Descriptor()
	// imagefolderpath.DefaultCreatedAt holds the default value on creation for the created_at field.
	imagefolderpath.DefaultCreatedAt = imagefolderpathDescCreatedAt.Default.(func() time.Time)
	imagefoldersourceMixin := schema.ImageFolderSource{}.Mixin()
	imagefoldersourceMixinFields0 := imagefoldersourceMixin[0].Fields()
	_ = imagefoldersourceMixinFields0
	imagefoldersourceFields := schema.ImageFolderSource{}.Fields()
	_ = imagefoldersourceFields
	// imagefoldersourceDescCreatedAt is the schema descriptor for created_at field.
	imagefoldersourceDescCreatedAt := imagefoldersourceMixinFields0[0].Descriptor()
	// imagefoldersource.DefaultCreatedAt holds the default value on creation for the created_at field.
	imagefoldersource.DefaultCreatedAt = imagefoldersourceDescCreatedAt.Default.(func() time.Time)
	imagesMixin := schema.Images{}.Mixin()
	imagesMixinFields0 := imagesMixin[0].Fields()
	_ = imagesMixinFields0
	imagesFields := schema.Images{}.Fields()
	_ = imagesFields
	// imagesDescCreatedAt is the schema descriptor for created_at field.
	imagesDescCreatedAt := imagesMixinFields0[0].Descriptor()
	// images.DefaultCreatedAt holds the default value on creation for the created_at field.
	images.DefaultCreatedAt = imagesDescCreatedAt.Default.(func() time.Time)
	infotypesMixin := schema.InfoTypes{}.Mixin()
	infotypesMixinFields0 := infotypesMixin[0].Fields()
	_ = infotypesMixinFields0
	infotypesFields := schema.InfoTypes{}.Fields()
	_ = infotypesFields
	// infotypesDescCreatedAt is the schema descriptor for created_at field.
	infotypesDescCreatedAt := infotypesMixinFields0[0].Descriptor()
	// infotypes.DefaultCreatedAt holds the default value on creation for the created_at field.
	infotypes.DefaultCreatedAt = infotypesDescCreatedAt.Default.(func() time.Time)
	pricetypeMixin := schema.PriceType{}.Mixin()
	pricetypeMixinFields0 := pricetypeMixin[0].Fields()
	_ = pricetypeMixinFields0
	pricetypeFields := schema.PriceType{}.Fields()
	_ = pricetypeFields
	// pricetypeDescCreatedAt is the schema descriptor for created_at field.
	pricetypeDescCreatedAt := pricetypeMixinFields0[0].Descriptor()
	// pricetype.DefaultCreatedAt holds the default value on creation for the created_at field.
	pricetype.DefaultCreatedAt = pricetypeDescCreatedAt.Default.(func() time.Time)
	producthasfeatureMixin := schema.ProductHasFeature{}.Mixin()
	producthasfeatureMixinFields0 := producthasfeatureMixin[0].Fields()
	_ = producthasfeatureMixinFields0
	producthasfeatureFields := schema.ProductHasFeature{}.Fields()
	_ = producthasfeatureFields
	// producthasfeatureDescCreatedAt is the schema descriptor for created_at field.
	producthasfeatureDescCreatedAt := producthasfeatureMixinFields0[0].Descriptor()
	// producthasfeature.DefaultCreatedAt holds the default value on creation for the created_at field.
	producthasfeature.DefaultCreatedAt = producthasfeatureDescCreatedAt.Default.(func() time.Time)
	producthasimageMixin := schema.ProductHasImage{}.Mixin()
	producthasimageMixinFields0 := producthasimageMixin[0].Fields()
	_ = producthasimageMixinFields0
	producthasimageFields := schema.ProductHasImage{}.Fields()
	_ = producthasimageFields
	// producthasimageDescCreatedAt is the schema descriptor for created_at field.
	producthasimageDescCreatedAt := producthasimageMixinFields0[0].Descriptor()
	// producthasimage.DefaultCreatedAt holds the default value on creation for the created_at field.
	producthasimage.DefaultCreatedAt = producthasimageDescCreatedAt.Default.(func() time.Time)
	producthasinfoMixin := schema.ProductHasInfo{}.Mixin()
	producthasinfoMixinFields0 := producthasinfoMixin[0].Fields()
	_ = producthasinfoMixinFields0
	producthasinfoFields := schema.ProductHasInfo{}.Fields()
	_ = producthasinfoFields
	// producthasinfoDescCreatedAt is the schema descriptor for created_at field.
	producthasinfoDescCreatedAt := producthasinfoMixinFields0[0].Descriptor()
	// producthasinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	producthasinfo.DefaultCreatedAt = producthasinfoDescCreatedAt.Default.(func() time.Time)
	producthasproductreferenceMixin := schema.ProductHasProductReference{}.Mixin()
	producthasproductreferenceMixinFields0 := producthasproductreferenceMixin[0].Fields()
	_ = producthasproductreferenceMixinFields0
	producthasproductreferenceFields := schema.ProductHasProductReference{}.Fields()
	_ = producthasproductreferenceFields
	// producthasproductreferenceDescCreatedAt is the schema descriptor for created_at field.
	producthasproductreferenceDescCreatedAt := producthasproductreferenceMixinFields0[0].Descriptor()
	// producthasproductreference.DefaultCreatedAt holds the default value on creation for the created_at field.
	producthasproductreference.DefaultCreatedAt = producthasproductreferenceDescCreatedAt.Default.(func() time.Time)
	productinfoMixin := schema.ProductInfo{}.Mixin()
	productinfoMixinFields0 := productinfoMixin[0].Fields()
	_ = productinfoMixinFields0
	productinfoFields := schema.ProductInfo{}.Fields()
	_ = productinfoFields
	// productinfoDescCreatedAt is the schema descriptor for created_at field.
	productinfoDescCreatedAt := productinfoMixinFields0[0].Descriptor()
	// productinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	productinfo.DefaultCreatedAt = productinfoDescCreatedAt.Default.(func() time.Time)
	productpricesMixin := schema.ProductPrices{}.Mixin()
	productpricesMixinFields0 := productpricesMixin[0].Fields()
	_ = productpricesMixinFields0
	productpricesFields := schema.ProductPrices{}.Fields()
	_ = productpricesFields
	// productpricesDescCreatedAt is the schema descriptor for created_at field.
	productpricesDescCreatedAt := productpricesMixinFields0[0].Descriptor()
	// productprices.DefaultCreatedAt holds the default value on creation for the created_at field.
	productprices.DefaultCreatedAt = productpricesDescCreatedAt.Default.(func() time.Time)
	productreferencesMixin := schema.ProductReferences{}.Mixin()
	productreferencesMixinFields0 := productreferencesMixin[0].Fields()
	_ = productreferencesMixinFields0
	productreferencesFields := schema.ProductReferences{}.Fields()
	_ = productreferencesFields
	// productreferencesDescCreatedAt is the schema descriptor for created_at field.
	productreferencesDescCreatedAt := productreferencesMixinFields0[0].Descriptor()
	// productreferences.DefaultCreatedAt holds the default value on creation for the created_at field.
	productreferences.DefaultCreatedAt = productreferencesDescCreatedAt.Default.(func() time.Time)
	productsMixin := schema.Products{}.Mixin()
	productsMixinFields0 := productsMixin[0].Fields()
	_ = productsMixinFields0
	productsFields := schema.Products{}.Fields()
	_ = productsFields
	// productsDescCreatedAt is the schema descriptor for created_at field.
	productsDescCreatedAt := productsMixinFields0[0].Descriptor()
	// products.DefaultCreatedAt holds the default value on creation for the created_at field.
	products.DefaultCreatedAt = productsDescCreatedAt.Default.(func() time.Time)
	promotionhasproductMixin := schema.PromotionHasProduct{}.Mixin()
	promotionhasproductMixinFields0 := promotionhasproductMixin[0].Fields()
	_ = promotionhasproductMixinFields0
	promotionhasproductFields := schema.PromotionHasProduct{}.Fields()
	_ = promotionhasproductFields
	// promotionhasproductDescCreatedAt is the schema descriptor for created_at field.
	promotionhasproductDescCreatedAt := promotionhasproductMixinFields0[0].Descriptor()
	// promotionhasproduct.DefaultCreatedAt holds the default value on creation for the created_at field.
	promotionhasproduct.DefaultCreatedAt = promotionhasproductDescCreatedAt.Default.(func() time.Time)
	promotionsMixin := schema.Promotions{}.Mixin()
	promotionsMixinFields0 := promotionsMixin[0].Fields()
	_ = promotionsMixinFields0
	promotionsFields := schema.Promotions{}.Fields()
	_ = promotionsFields
	// promotionsDescCreatedAt is the schema descriptor for created_at field.
	promotionsDescCreatedAt := promotionsMixinFields0[0].Descriptor()
	// promotions.DefaultCreatedAt holds the default value on creation for the created_at field.
	promotions.DefaultCreatedAt = promotionsDescCreatedAt.Default.(func() time.Time)
	referencesourcesMixin := schema.ReferenceSources{}.Mixin()
	referencesourcesMixinFields0 := referencesourcesMixin[0].Fields()
	_ = referencesourcesMixinFields0
	referencesourcesFields := schema.ReferenceSources{}.Fields()
	_ = referencesourcesFields
	// referencesourcesDescCreatedAt is the schema descriptor for created_at field.
	referencesourcesDescCreatedAt := referencesourcesMixinFields0[0].Descriptor()
	// referencesources.DefaultCreatedAt holds the default value on creation for the created_at field.
	referencesources.DefaultCreatedAt = referencesourcesDescCreatedAt.Default.(func() time.Time)
	toolhasproductMixin := schema.ToolHasProduct{}.Mixin()
	toolhasproductMixinFields0 := toolhasproductMixin[0].Fields()
	_ = toolhasproductMixinFields0
	toolhasproductFields := schema.ToolHasProduct{}.Fields()
	_ = toolhasproductFields
	// toolhasproductDescCreatedAt is the schema descriptor for created_at field.
	toolhasproductDescCreatedAt := toolhasproductMixinFields0[0].Descriptor()
	// toolhasproduct.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolhasproduct.DefaultCreatedAt = toolhasproductDescCreatedAt.Default.(func() time.Time)
	toolsMixin := schema.Tools{}.Mixin()
	toolsMixinFields0 := toolsMixin[0].Fields()
	_ = toolsMixinFields0
	toolsFields := schema.Tools{}.Fields()
	_ = toolsFields
	// toolsDescCreatedAt is the schema descriptor for created_at field.
	toolsDescCreatedAt := toolsMixinFields0[0].Descriptor()
	// tools.DefaultCreatedAt holds the default value on creation for the created_at field.
	tools.DefaultCreatedAt = toolsDescCreatedAt.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescSurname is the schema descriptor for Surname field.
	userDescSurname := userFields[1].Descriptor()
	// user.SurnameValidator is a validator for the "Surname" field. It is called by the builders before save.
	user.SurnameValidator = userDescSurname.Validators[0].(func(string) error)
	varianttypeMixin := schema.VariantType{}.Mixin()
	varianttypeMixinFields0 := varianttypeMixin[0].Fields()
	_ = varianttypeMixinFields0
	varianttypeFields := schema.VariantType{}.Fields()
	_ = varianttypeFields
	// varianttypeDescCreatedAt is the schema descriptor for created_at field.
	varianttypeDescCreatedAt := varianttypeMixinFields0[0].Descriptor()
	// varianttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	varianttype.DefaultCreatedAt = varianttypeDescCreatedAt.Default.(func() time.Time)
}
