// Code generated by ent, DO NOT EDIT.

package featuresunitvalues

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the featuresunitvalues type in the database.
	Label = "features_unit_values"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDecimals holds the string denoting the decimals field in the database.
	FieldDecimals = "decimals"
	// EdgeFeatureValues holds the string denoting the feature_values edge name in mutations.
	EdgeFeatureValues = "feature_values"
	// Table holds the table name of the featuresunitvalues in the database.
	Table = "features_unit_values"
	// FeatureValuesTable is the table that holds the feature_values relation/edge.
	FeatureValuesTable = "features_values"
	// FeatureValuesInverseTable is the table name for the FeaturesValues entity.
	// It exists in this package in order to avoid circular dependency with the "featuresvalues" package.
	FeatureValuesInverseTable = "features_values"
	// FeatureValuesColumn is the table column denoting the feature_values relation/edge.
	FeatureValuesColumn = "feature_unit_values_id"
)

// Columns holds all SQL columns for featuresunitvalues fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDecimals,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the FeaturesUnitValues queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDecimals orders the results by the decimals field.
func ByDecimals(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecimals, opts...).ToFunc()
}

// ByFeatureValuesCount orders the results by feature_values count.
func ByFeatureValuesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFeatureValuesStep(), opts...)
	}
}

// ByFeatureValues orders the results by feature_values terms.
func ByFeatureValues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFeatureValuesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFeatureValuesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FeatureValuesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FeatureValuesTable, FeatureValuesColumn),
	)
}
